### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by mrmartineau** [mrmartineau/KOglossaryLinks#1]
- [x] Add build scripts
- [x] Improve readme
- [ ] Improve and expand examples
- [x] Add to npm (http://blog.npmjs.org/post/111475741445/publishing-your-jquery-plugin-to-npm-the-quick)
- [x] Add to Bower
- [ ] Enable use with module loaders and npm
